INSERT INTO SECURITY (ID, TICKER, MATURITY, SECURITY_TYPE, PRICE,STRIKE_PRICE, MU, SIGMA) VALUES (1,'AAPL', null, 'STOCK', 100.0, null, .50,.35);
INSERT INTO SECURITY (ID, TICKER, MATURITY, SECURITY_TYPE, PRICE,STRIKE_PRICE, MU, SIGMA) VALUES (2,'TESLA', null, 'STOCK', 450.0, null, .45,.35);
INSERT INTO SECURITY (ID, TICKER, MATURITY, SECURITY_TYPE, PRICE,STRIKE_PRICE) VALUES (3,'AAPL-OCT-2020-110-C', .3, 'CALL', null, 110.0);
INSERT INTO SECURITY (ID, TICKER, MATURITY, SECURITY_TYPE, PRICE,STRIKE_PRICE) VALUES (4,'AAPL-OCT-2020-110-P', .3, 'PUT', null, 110.0);
INSERT INTO SECURITY (ID, TICKER, MATURITY, SECURITY_TYPE, PRICE,STRIKE_PRICE) VALUES (5,'TESLA-NOV-2020-400-C', .2, 'CALL', null, 400.0);
INSERT INTO SECURITY (ID, TICKER, MATURITY, SECURITY_TYPE, PRICE,STRIKE_PRICE) VALUES (6,'TESLA-DEC-2020-400-P', .2, 'PUT', null, 400.0);