DROP TABLE IF EXISTS SECURITY;
CREATE TABLE SECURITY (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    ticker VARCHAR(250) NOT NULL,
    maturity VARCHAR(250) NULL,
    security_Type VARCHAR(10) NOT NULL,
    price NUMERIC NULL,
    strike_Price NUMERIC NULL,
    mu NUMERIC NULL,
    sigma NUMERIC NULL
);